# This file contains values from Cookiecutter

default_context:
  project_name: "honeyfruits"
  project_description: "Awesome `honeyfruits` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "david"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "wtydavid99"
  email: "wty.david@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
